
export const SYSTEM_FIELDS: Record<string, ModelFieldSchema> = {
  _id: {
    type: 'string',
    title: 'id',
    readOnly: false,
    display: false,
    'x-component': 'Input',
    not_null: false,
    'x-internal': { isSystem: true },
    'x-index': 0,
  },
  created_at: {
    type: 'datetime',
    title: '创建时间',
    readOnly: false,
    display: false,
    'x-component': 'DatePicker',
    not_null: false,
    'x-component-props': { isNow: false, showTime: false },
    'x-internal': { isSystem: true },
    'x-index': 0,
  },
  updated_at: {
    type: 'datetime',
    title: '修改时间',
    readOnly: false,
    display: false,
    'x-component': 'DatePicker',
    not_null: false,
    'x-component-props': { isNow: false, showTime: false },
    'x-internal': { isSystem: true },
    'x-index': 0,
  },
  creator_name: {
    type: 'string',
    title: '创建者',
    readOnly: false,
    display: false,
    not_null: false,
    'x-component': 'Input',
    'x-internal': { isSystem: true },
    'x-index': 0,
  },
  creator_id: {
    type: 'string',
    title: '创建者 ID',
    readOnly: false,
    display: false,
    'x-component': 'Input',
    not_null: false,
    'x-internal': { isSystem: true },
    'x-index': 0,
  },
  modifier_name: {
    type: 'string',
    title: '修改者',
    readOnly: false,
    display: false,
    'x-component': 'Input',
    not_null: false,
    'x-internal': { isSystem: true },
    'x-index': 0,
  },
  modifier_id: {
    type: 'string',
    title: '修改者 ID',
    readOnly: false,
    display: false,
    'x-component': 'Input',
    not_null: false,
    'x-internal': { isSystem: true },
    'x-index': 0,
  },
};

