export const designTokenData = [
  {
    value: '2',
    type: 'borderRadius',
    unit: 'px',
    name: 'borderRadius.xs',
    parent: 'global',
    rawValue: '2',
    resolveFailed: false,
  },
  {
    value: '4',
    type: 'borderRadius',
    unit: 'px',
    name: 'borderRadius.sm',
    parent: 'global',
    rawValue: '4',
    resolveFailed: false,
  },
  {
    value: '8',
    type: 'borderRadius',
    unit: 'px',
    name: 'borderRadius.md',
    parent: 'global',
    rawValue: '8',
    resolveFailed: false,
  },
  {
    value: '12',
    type: 'borderRadius',
    unit: 'px',
    name: 'borderRadius.lg',
    parent: 'global',
    rawValue: '12',
    resolveFailed: false,
  },
  {
    value: '16',
    type: 'borderRadius',
    unit: 'px',
    name: 'borderRadius.xl',
    parent: 'global',
    rawValue: '16',
    resolveFailed: false,
  },
  {
    value: '50',
    type: 'borderRadius',
    unit: '%',
    name: 'borderRadius.round',
    parent: 'global',
    rawValue: '50',
    resolveFailed: false,
  },
  {
    value: '0',
    type: 'borderWidth',
    unit: 'px',
    name: 'borderWidth.none',
    parent: 'global',
    rawValue: '0',
    resolveFailed: false,
  },
  {
    value: '1',
    type: 'borderWidth',
    unit: 'px',
    name: 'borderWidth.xs',
    parent: 'global',
    rawValue: '1',
    resolveFailed: false,
  },
  {
    value: '2',
    type: 'borderWidth',
    unit: 'px',
    name: 'borderWidth.sm',
    parent: 'global',
    rawValue: '2',
    resolveFailed: false,
  },
  {
    value: '4',
    type: 'borderWidth',
    unit: 'px',
    name: 'borderWidth.md',
    parent: 'global',
    rawValue: '4',
    resolveFailed: false,
  },
  {
    value: '8',
    type: 'borderWidth',
    unit: 'px',
    name: 'borderWidth.lg',
    parent: 'global',
    rawValue: '8',
    resolveFailed: false,
  },
  {
    value: '#000000',
    type: 'color',
    name: 'base.black',
    parent: 'global',
    rawValue: '#000000',
    resolveFailed: false,
  },
  {
    value: '#ffffff',
    type: 'color',
    name: 'base.white',
    parent: 'global',
    rawValue: '#ffffff',
    resolveFailed: false,
  },
  {
    value: '#f8fafc',
    type: 'color',
    name: 'neu.50',
    parent: 'global',
    rawValue: '#f8fafc',
    resolveFailed: false,
  },
  {
    value: '#f1f5f9',
    type: 'color',
    name: 'neu.100',
    parent: 'global',
    rawValue: '#f1f5f9',
    resolveFailed: false,
  },
  {
    value: '#e2e8f0',
    type: 'color',
    name: 'neu.200',
    parent: 'global',
    rawValue: '#e2e8f0',
    resolveFailed: false,
  },
  {
    value: '#cbd5e1',
    type: 'color',
    name: 'neu.300',
    parent: 'global',
    rawValue: '#cbd5e1',
    resolveFailed: false,
  },
  {
    value: '#94a3b8',
    type: 'color',
    name: 'neu.400',
    parent: 'global',
    rawValue: '#94a3b8',
    resolveFailed: false,
  },
  {
    value: '#64748b',
    type: 'color',
    name: 'neu.500',
    parent: 'global',
    rawValue: '#64748b',
    resolveFailed: false,
  },
  {
    value: '#475569',
    type: 'color',
    name: 'neu.600',
    parent: 'global',
    rawValue: '#475569',
    resolveFailed: false,
  },
  {
    value: '#334155',
    type: 'color',
    name: 'neu.700',
    parent: 'global',
    rawValue: '#334155',
    resolveFailed: false,
  },
  {
    value: '#1e293b',
    type: 'color',
    name: 'neu.800',
    parent: 'global',
    rawValue: '#1e293b',
    resolveFailed: false,
  },
  {
    value: '#0f172a',
    type: 'color',
    name: 'neu.900',
    parent: 'global',
    rawValue: '#0f172a',
    resolveFailed: false,
  },
  {
    value: '#fff2f0',
    type: 'color',
    name: 'red.50',
    parent: 'global',
    rawValue: '#fff2f0',
    resolveFailed: false,
  },
  {
    value: '#ffd5cf',
    type: 'color',
    name: 'red.100',
    parent: 'global',
    rawValue: '#ffd5cf',
    resolveFailed: false,
  },
  {
    value: '#ffafa6',
    type: 'color',
    name: 'red.200',
    parent: 'global',
    rawValue: '#ffafa6',
    resolveFailed: false,
  },
  {
    value: '#f58078',
    type: 'color',
    name: 'red.300',
    parent: 'global',
    rawValue: '#f58078',
    resolveFailed: false,
  },
  {
    value: '#e8524d',
    type: 'color',
    name: 'red.400',
    parent: 'global',
    rawValue: '#e8524d',
    resolveFailed: false,
  },
  {
    value: '#dc2626',
    type: 'color',
    name: 'red.500',
    parent: 'global',
    rawValue: '#dc2626',
    resolveFailed: false,
  },
  {
    value: '#b5161b',
    type: 'color',
    name: 'red.600',
    parent: 'global',
    rawValue: '#b5161b',
    resolveFailed: false,
  },
  {
    value: '#8f0a13',
    type: 'color',
    name: 'red.700',
    parent: 'global',
    rawValue: '#8f0a13',
    resolveFailed: false,
  },
  {
    value: '#69020c',
    type: 'color',
    name: 'red.800',
    parent: 'global',
    rawValue: '#69020c',
    resolveFailed: false,
  },
  {
    value: '#420109',
    type: 'color',
    name: 'red.900',
    parent: 'global',
    rawValue: '#420109',
    resolveFailed: false,
  },
  {
    value: '#fff3e6',
    type: 'color',
    name: 'orange.50',
    parent: 'global',
    rawValue: '#fff3e6',
    resolveFailed: false,
  },
  {
    value: '#ffd6b0',
    type: 'color',
    name: 'orange.100',
    parent: 'global',
    rawValue: '#ffd6b0',
    resolveFailed: false,
  },
  {
    value: '#ffbd87',
    type: 'color',
    name: 'orange.200',
    parent: 'global',
    rawValue: '#ffbd87',
    resolveFailed: false,
  },
  {
    value: '#ffa15e',
    type: 'color',
    name: 'orange.300',
    parent: 'global',
    rawValue: '#ffa15e',
    resolveFailed: false,
  },
  {
    value: '#f97316',
    type: 'color',
    name: 'orange.400',
    parent: 'global',
    rawValue: '#f97316',
    resolveFailed: false,
  },
  {
    value: '#ea580c',
    type: 'color',
    name: 'orange.500',
    parent: 'global',
    rawValue: '#ea580c',
    resolveFailed: false,
  },
  {
    value: '#c43e00',
    type: 'color',
    name: 'orange.600',
    parent: 'global',
    rawValue: '#c43e00',
    resolveFailed: false,
  },
  {
    value: '#9e2d00',
    type: 'color',
    name: 'orange.700',
    parent: 'global',
    rawValue: '#9e2d00',
    resolveFailed: false,
  },
  {
    value: '#781e00',
    type: 'color',
    name: 'orange.800',
    parent: 'global',
    rawValue: '#781e00',
    resolveFailed: false,
  },
  {
    value: '#521200',
    type: 'color',
    name: 'orange.900',
    parent: 'global',
    rawValue: '#521200',
    resolveFailed: false,
  },
  {
    value: '#fff7e6',
    type: 'color',
    name: 'yellow.50',
    parent: 'global',
    rawValue: '#fff7e6',
    resolveFailed: false,
  },
  {
    value: '#ffe3ab',
    type: 'color',
    name: 'yellow.100',
    parent: 'global',
    rawValue: '#ffe3ab',
    resolveFailed: false,
  },
  {
    value: '#ffd182',
    type: 'color',
    name: 'yellow.200',
    parent: 'global',
    rawValue: '#ffd182',
    resolveFailed: false,
  },
  {
    value: '#f2b355',
    type: 'color',
    name: 'yellow.300',
    parent: 'global',
    rawValue: '#f2b355',
    resolveFailed: false,
  },
  {
    value: '#e6952c',
    type: 'color',
    name: 'yellow.400',
    parent: 'global',
    rawValue: '#e6952c',
    resolveFailed: false,
  },
  {
    value: '#d97706',
    type: 'color',
    name: 'yellow.500',
    parent: 'global',
    rawValue: '#d97706',
    resolveFailed: false,
  },
  {
    value: '#b35900',
    type: 'color',
    name: 'yellow.600',
    parent: 'global',
    rawValue: '#b35900',
    resolveFailed: false,
  },
  {
    value: '#8c4100',
    type: 'color',
    name: 'yellow.700',
    parent: 'global',
    rawValue: '#8c4100',
    resolveFailed: false,
  },
  {
    value: '#662c00',
    type: 'color',
    name: 'yellow.800',
    parent: 'global',
    rawValue: '#662c00',
    resolveFailed: false,
  },
  {
    value: '#401a00',
    type: 'color',
    name: 'yellow.900',
    parent: 'global',
    rawValue: '#401a00',
    resolveFailed: false,
  },
  {
    value: '#e6f5e9',
    type: 'color',
    name: 'green.50',
    parent: 'global',
    rawValue: '#e6f5e9',
    resolveFailed: false,
  },
  {
    value: '#b0e8be',
    type: 'color',
    name: 'green.100',
    parent: 'global',
    rawValue: '#b0e8be',
    resolveFailed: false,
  },
  {
    value: '#84db9c',
    type: 'color',
    name: 'green.200',
    parent: 'global',
    rawValue: '#84db9c',
    resolveFailed: false,
  },
  {
    value: '#5bcf80',
    type: 'color',
    name: 'green.300',
    parent: 'global',
    rawValue: '#5bcf80',
    resolveFailed: false,
  },
  {
    value: '#36c267',
    type: 'color',
    name: 'green.400',
    parent: 'global',
    rawValue: '#36c267',
    resolveFailed: false,
  },
  {
    value: '#1cb552',
    type: 'color',
    name: 'green.500',
    parent: 'global',
    rawValue: '#1cb552',
    resolveFailed: false,
  },
  {
    value: '#0e8f40',
    type: 'color',
    name: 'green.600',
    parent: 'global',
    rawValue: '#0e8f40',
    resolveFailed: false,
  },
  {
    value: '#026930',
    type: 'color',
    name: 'green.700',
    parent: 'global',
    rawValue: '#026930',
    resolveFailed: false,
  },
  {
    value: '#004220',
    type: 'color',
    name: 'green.800',
    parent: 'global',
    rawValue: '#004220',
    resolveFailed: false,
  },
  {
    value: '#001c0e',
    type: 'color',
    name: 'green.900',
    parent: 'global',
    rawValue: '#001c0e',
    resolveFailed: false,
  },
  {
    value: '#e1f5ef',
    type: 'color',
    name: 'teal.50',
    parent: 'global',
    rawValue: '#e1f5ef',
    resolveFailed: false,
  },
  {
    value: '#b0e8d9',
    type: 'color',
    name: 'teal.100',
    parent: 'global',
    rawValue: '#b0e8d9',
    resolveFailed: false,
  },
  {
    value: '#84dbc7',
    type: 'color',
    name: 'teal.200',
    parent: 'global',
    rawValue: '#84dbc7',
    resolveFailed: false,
  },
  {
    value: '#5bcfb7',
    type: 'color',
    name: 'teal.300',
    parent: 'global',
    rawValue: '#5bcfb7',
    resolveFailed: false,
  },
  {
    value: '#36c2ab',
    type: 'color',
    name: 'teal.400',
    parent: 'global',
    rawValue: '#36c2ab',
    resolveFailed: false,
  },
  {
    value: '#16b59f',
    type: 'color',
    name: 'teal.500',
    parent: 'global',
    rawValue: '#16b59f',
    resolveFailed: false,
  },
  {
    value: '#0a8f82',
    type: 'color',
    name: 'teal.600',
    parent: 'global',
    rawValue: '#0a8f82',
    resolveFailed: false,
  },
  {
    value: '#026962',
    type: 'color',
    name: 'teal.700',
    parent: 'global',
    rawValue: '#026962',
    resolveFailed: false,
  },
  {
    value: '#004240',
    type: 'color',
    name: 'teal.800',
    parent: 'global',
    rawValue: '#004240',
    resolveFailed: false,
  },
  {
    value: '#001c1c',
    type: 'color',
    name: 'teal.900',
    parent: 'global',
    rawValue: '#001c1c',
    resolveFailed: false,
  },
  {
    value: '#f0f6ff',
    type: 'color',
    name: 'blue.50',
    parent: 'global',
    rawValue: '#f0f6ff',
    resolveFailed: false,
  },
  {
    value: '#dee9ff',
    type: 'color',
    name: 'blue.100',
    parent: 'global',
    rawValue: '#dee9ff',
    resolveFailed: false,
  },
  {
    value: '#b5ccff',
    type: 'color',
    name: 'blue.200',
    parent: 'global',
    rawValue: '#b5ccff',
    resolveFailed: false,
  },
  {
    value: '#8cadff',
    type: 'color',
    name: 'blue.300',
    parent: 'global',
    rawValue: '#8cadff',
    resolveFailed: false,
  },
  {
    value: '#638aff',
    type: 'color',
    name: 'blue.400',
    parent: 'global',
    rawValue: '#638aff',
    resolveFailed: false,
  },
  {
    value: '#375ff3',
    type: 'color',
    name: 'blue.500',
    parent: 'global',
    rawValue: '#375ff3',
    resolveFailed: false,
  },
  {
    value: '#2543cc',
    type: 'color',
    name: 'blue.600',
    parent: 'global',
    rawValue: '#2543cc',
    resolveFailed: false,
  },
  {
    value: '#162ba6',
    type: 'color',
    name: 'blue.700',
    parent: 'global',
    rawValue: '#162ba6',
    resolveFailed: false,
  },
  {
    value: '#0a1880',
    type: 'color',
    name: 'blue.800',
    parent: 'global',
    rawValue: '#0a1880',
    resolveFailed: false,
  },
  {
    value: '#060d59',
    type: 'color',
    name: 'blue.900',
    parent: 'global',
    rawValue: '#060d59',
    resolveFailed: false,
  },
  {
    value: '#e6fcfc',
    type: 'color',
    name: 'cyan.50',
    parent: 'global',
    rawValue: '#e6fcfc',
    resolveFailed: false,
  },
  {
    value: '#b4ecf0',
    type: 'color',
    name: 'cyan.100',
    parent: 'global',
    rawValue: '#b4ecf0',
    resolveFailed: false,
  },
  {
    value: '#86dae3',
    type: 'color',
    name: 'cyan.200',
    parent: 'global',
    rawValue: '#86dae3',
    resolveFailed: false,
  },
  {
    value: '#5cc6d6',
    type: 'color',
    name: 'cyan.300',
    parent: 'global',
    rawValue: '#5cc6d6',
    resolveFailed: false,
  },
  {
    value: '#36b1c9',
    type: 'color',
    name: 'cyan.400',
    parent: 'global',
    rawValue: '#36b1c9',
    resolveFailed: false,
  },
  {
    value: '#159abc',
    type: 'color',
    name: 'cyan.500',
    parent: 'global',
    rawValue: '#159abc',
    resolveFailed: false,
  },
  {
    value: '#097596',
    type: 'color',
    name: 'cyan.600',
    parent: 'global',
    rawValue: '#097596',
    resolveFailed: false,
  },
  {
    value: '#015370',
    type: 'color',
    name: 'cyan.700',
    parent: 'global',
    rawValue: '#015370',
    resolveFailed: false,
  },
  {
    value: '#00344a',
    type: 'color',
    name: 'cyan.800',
    parent: 'global',
    rawValue: '#00344a',
    resolveFailed: false,
  },
  {
    value: '#001824',
    type: 'color',
    name: 'cyan.900',
    parent: 'global',
    rawValue: '#001824',
    resolveFailed: false,
  },
  {
    value: '#f4f0ff',
    type: 'color',
    name: 'indigo.50',
    parent: 'global',
    rawValue: '#f4f0ff',
    resolveFailed: false,
  },
  {
    value: '#dfd6ff',
    type: 'color',
    name: 'indigo.100',
    parent: 'global',
    rawValue: '#dfd6ff',
    resolveFailed: false,
  },
  {
    value: '#bcadff',
    type: 'color',
    name: 'indigo.200',
    parent: 'global',
    rawValue: '#bcadff',
    resolveFailed: false,
  },
  {
    value: '#917ff5',
    type: 'color',
    name: 'indigo.300',
    parent: 'global',
    rawValue: '#917ff5',
    resolveFailed: false,
  },
  {
    value: '#6554e8',
    type: 'color',
    name: 'indigo.400',
    parent: 'global',
    rawValue: '#6554e8',
    resolveFailed: false,
  },
  {
    value: '#3b2cdb',
    type: 'color',
    name: 'indigo.500',
    parent: 'global',
    rawValue: '#3b2cdb',
    resolveFailed: false,
  },
  {
    value: '#231bb5',
    type: 'color',
    name: 'indigo.600',
    parent: 'global',
    rawValue: '#231bb5',
    resolveFailed: false,
  },
  {
    value: '#8c4100',
    type: 'color',
    name: 'indigo.700',
    parent: 'global',
    rawValue: '#8c4100',
    resolveFailed: false,
  },
  {
    value: '#662c00',
    type: 'color',
    name: 'indigo.800',
    parent: 'global',
    rawValue: '#662c00',
    resolveFailed: false,
  },
  {
    value: '#401a00',
    type: 'color',
    name: 'indigo.900',
    parent: 'global',
    rawValue: '#401a00',
    resolveFailed: false,
  },
  {
    value: '#faf0ff',
    type: 'color',
    name: 'purple.50',
    parent: 'global',
    rawValue: '#faf0ff',
    resolveFailed: false,
  },
  {
    value: '#f3dbff',
    type: 'color',
    name: 'purple.100',
    parent: 'global',
    rawValue: '#f3dbff',
    resolveFailed: false,
  },
  {
    value: '#e2b3ff',
    type: 'color',
    name: 'purple.200',
    parent: 'global',
    rawValue: '#e2b3ff',
    resolveFailed: false,
  },
  {
    value: '#ce8aff',
    type: 'color',
    name: 'purple.300',
    parent: 'global',
    rawValue: '#ce8aff',
    resolveFailed: false,
  },
  {
    value: '#b25ef7',
    type: 'color',
    name: 'purple.400',
    parent: 'global',
    rawValue: '#b25ef7',
    resolveFailed: false,
  },
  {
    value: '#9333ea',
    type: 'color',
    name: 'purple.500',
    parent: 'global',
    rawValue: '#9333ea',
    resolveFailed: false,
  },
  {
    value: '#7021c4',
    type: 'color',
    name: 'purple.600',
    parent: 'global',
    rawValue: '#7021c4',
    resolveFailed: false,
  },
  {
    value: '#52139e',
    type: 'color',
    name: 'purple.700',
    parent: 'global',
    rawValue: '#52139e',
    resolveFailed: false,
  },
  {
    value: '#370878',
    type: 'color',
    name: 'purple.800',
    parent: 'global',
    rawValue: '#370878',
    resolveFailed: false,
  },
  {
    value: '#220552',
    type: 'color',
    name: 'purple.900',
    parent: 'global',
    rawValue: '#220552',
    resolveFailed: false,
  },
  {
    value: '#fff0fe',
    type: 'color',
    name: 'fuchsia.50',
    parent: 'global',
    rawValue: '#fff0fe',
    resolveFailed: false,
  },
  {
    value: '#ffd1fe',
    type: 'color',
    name: 'fuchsia.100',
    parent: 'global',
    rawValue: '#ffd1fe',
    resolveFailed: false,
  },
  {
    value: '#f8a5fa',
    type: 'color',
    name: 'fuchsia.200',
    parent: 'global',
    rawValue: '#f8a5fa',
    resolveFailed: false,
  },
  {
    value: '#e777ed',
    type: 'color',
    name: 'fuchsia.300',
    parent: 'global',
    rawValue: '#e777ed',
    resolveFailed: false,
  },
  {
    value: '#d44ce0',
    type: 'color',
    name: 'fuchsia.400',
    parent: 'global',
    rawValue: '#d44ce0',
    resolveFailed: false,
  },
  {
    value: '#c026d3',
    type: 'color',
    name: 'fuchsia.500',
    parent: 'global',
    rawValue: '#c026d3',
    resolveFailed: false,
  },
  {
    value: '#9717ad',
    type: 'color',
    name: 'fuchsia.600',
    parent: 'global',
    rawValue: '#9717ad',
    resolveFailed: false,
  },
  {
    value: '#700b87',
    type: 'color',
    name: 'fuchsia.700',
    parent: 'global',
    rawValue: '#700b87',
    resolveFailed: false,
  },
  {
    value: '#4d0361',
    type: 'color',
    name: 'fuchsia.800',
    parent: 'global',
    rawValue: '#4d0361',
    resolveFailed: false,
  },
  {
    value: '#2c013b',
    type: 'color',
    name: 'fuchsia.900',
    parent: 'global',
    rawValue: '#2c013b',
    resolveFailed: false,
  },
  {
    value: 'rgba(30,41,59,0.65)',
    type: 'color',
    name: 'opacity-color.mask',
    parent: 'global',
    rawValue: 'rgba(30,41,59,0.65)',
    resolveFailed: false,
  },
  {
    value: 'rgba(54,194,103,0.15)',
    type: 'color',
    name: 'opacity-color.app1',
    parent: 'global',
    rawValue: 'rgba(54,194,103,0.15)',
    resolveFailed: false,
  },
  {
    value: 'rgba(230,149,44,0.15)',
    type: 'color',
    name: 'opacity-color.app2',
    parent: 'global',
    rawValue: 'rgba(230,149,44,0.15)',
    resolveFailed: false,
  },
  {
    value: 'rgba(54,194,171,0.15)',
    type: 'color',
    name: 'opacity-color.app3',
    parent: 'global',
    rawValue: 'rgba(54,194,171,0.15)',
    resolveFailed: false,
  },
  {
    value: 'rgba(249,115,22,0.15)',
    type: 'color',
    name: 'opacity-color.app4',
    parent: 'global',
    rawValue: 'rgba(249,115,22,0.15)',
    resolveFailed: false,
  },
  {
    value: 'rgba(54,178,201,0.15)',
    type: 'color',
    name: 'opacity-color.app5',
    parent: 'global',
    rawValue: 'rgba(54,178,201,0.15)',
    resolveFailed: false,
  },
  {
    value: 'rgba(178,94,247,0.15)',
    type: 'color',
    name: 'opacity-color.app6',
    parent: 'global',
    rawValue: 'rgba(178,94,247,0.15)',
    resolveFailed: false,
  },
  {
    value: 'rgba(101,84,232,0.15)',
    type: 'color',
    name: 'opacity-color.app7',
    parent: 'global',
    rawValue: 'rgba(101,84,232,0.15)',
    resolveFailed: false,
  },
  {
    value: 'rgba(212,76,224,0.15)',
    type: 'color',
    name: 'opacity-color.app8',
    parent: 'global',
    rawValue: 'rgba(212,76,224,0.15)',
    resolveFailed: false,
  },
  {
    value: 'rgba(99,138,255,0.15)',
    type: 'color',
    name: 'opacity-color.app9',
    parent: 'global',
    rawValue: 'rgba(99,138,255,0.15)',
    resolveFailed: false,
  },
  {
    value: 'rgba(232,82,77,0.15)',
    type: 'color',
    name: 'opacity-color.app10',
    parent: 'global',
    rawValue: 'rgba(232,82,77,0.15)',
    resolveFailed: false,
  },
  {
    value: '10',
    type: 'opacity',
    unit: '%',
    name: 'opacity.low',
    parent: 'global',
    rawValue: '10',
    resolveFailed: false,
  },
  {
    value: '50',
    type: 'opacity',
    unit: '%',
    name: 'opacity.md',
    parent: 'global',
    rawValue: '50',
    resolveFailed: false,
  },
  {
    value: '90',
    type: 'opacity',
    unit: '%',
    name: 'opacity.high',
    parent: 'global',
    rawValue: '90',
    resolveFailed: false,
  },
  {
    value: 'inherit',
    type: 'fontFamily',
    name: 'fontFamily.inherit',
    parent: 'global',
    rawValue: 'inherit',
    resolveFailed: false,
  },
  {
    value: 'SimSun, sans-serif',
    type: 'fontFamily',
    name: 'fontFamily.simsun',
    parent: 'global',
    rawValue: 'SimSun, sans-serif',
    resolveFailed: false,
  },
  {
    value: 'Roboto, sans-serif',
    type: 'fontFamily',
    name: 'fontFamily.roboto',
    parent: 'global',
    rawValue: 'Roboto, sans-serif',
    resolveFailed: false,
  },
  {
    value: '75',
    type: 'lineHeight',
    unit: '%',
    name: 'lineHeight.xs',
    parent: 'global',
    rawValue: '75',
    resolveFailed: false,
  },
  {
    value: '100',
    type: 'lineHeight',
    unit: '%',
    name: 'lineHeight.sm',
    parent: 'global',
    rawValue: '100',
    resolveFailed: false,
  },
  {
    value: '125',
    type: 'lineHeight',
    unit: '%',
    name: 'lineHeight.md',
    parent: 'global',
    rawValue: '125',
    resolveFailed: false,
  },
  {
    value: '150',
    type: 'lineHeight',
    unit: '%',
    name: 'lineHeight.lg',
    parent: 'global',
    rawValue: '150',
    resolveFailed: false,
  },
  {
    value: '175',
    type: 'lineHeight',
    unit: '%',
    name: 'lineHeight.xl',
    parent: 'global',
    rawValue: '175',
    resolveFailed: false,
  },
  {
    value: '200',
    type: 'lineHeight',
    unit: '%',
    name: 'lineHeight.xxl',
    parent: 'global',
    rawValue: '200',
    resolveFailed: false,
  },
  {
    value: '400',
    type: 'fontWeight',
    name: 'fontWeight.regular',
    parent: 'global',
    rawValue: '400',
    resolveFailed: false,
  },
  {
    value: '500',
    type: 'fontWeight',
    name: 'fontWeight.bold',
    parent: 'global',
    rawValue: '500',
    resolveFailed: false,
  },
  {
    value: '12',
    type: 'fontSize',
    unit: 'px',
    name: 'fontSize.xs',
    parent: 'global',
    rawValue: '12',
    resolveFailed: false,
  },
  {
    value: '14',
    type: 'fontSize',
    unit: 'px',
    name: 'fontSize.sm',
    parent: 'global',
    rawValue: '14',
    resolveFailed: false,
  },
  {
    value: '16',
    type: 'fontSize',
    unit: 'px',
    name: 'fontSize.md',
    parent: 'global',
    rawValue: '16',
    resolveFailed: false,
  },
  {
    value: '18',
    type: 'fontSize',
    unit: 'px',
    name: 'fontSize.lg',
    parent: 'global',
    rawValue: '18',
    resolveFailed: false,
  },
  {
    value: '20',
    type: 'fontSize',
    unit: 'px',
    name: 'fontSize.xl',
    parent: 'global',
    rawValue: '20',
    resolveFailed: false,
  },
  {
    value: '22',
    type: 'fontSize',
    unit: 'px',
    name: 'fontSize.xxl',
    parent: 'global',
    rawValue: '22',
    resolveFailed: false,
  },
  {
    value: '24',
    type: 'fontSize',
    unit: 'px',
    name: 'fontSize.xxxl',
    parent: 'global',
    rawValue: '24',
    resolveFailed: false,
  },
  {
    type: 'typography',
    value: {
      fontFamily: 'inherit',
      fontWeight: '500',
      lineHeight: '125',
      fontSize: '24',
      textDecoration: 'none',
    },
    unit: {
      lineHeight: '%',
      fontSize: 'px',
    },
    name: 'typography.title.h1',
    parent: 'global',
    rawValue: {
      fontFamily: '{fontFamily.inherit}',
      fontWeight: '{fontWeight.bold}',
      lineHeight: '{lineHeight.md}',
      fontSize: '{fontSize.xxxl}',
      textDecoration: '{textDecoration.none}',
    },
  },
  {
    type: 'typography',
    value: {
      fontFamily: 'inherit',
      fontWeight: '500',
      lineHeight: '125',
      fontSize: '20',
      textDecoration: 'none',
    },
    unit: {
      lineHeight: '%',
      fontSize: 'px',
    },
    name: 'typography.title.h2',
    parent: 'global',
    rawValue: {
      fontFamily: '{fontFamily.inherit}',
      fontWeight: '{fontWeight.bold}',
      lineHeight: '{lineHeight.md}',
      fontSize: '{fontSize.xl}',
      textDecoration: '{textDecoration.none}',
    },
  },
  {
    type: 'typography',
    value: {
      fontFamily: 'inherit',
      fontWeight: '500',
      lineHeight: '150',
      fontSize: '16',
      textDecoration: 'none',
    },
    unit: {
      lineHeight: '%',
      fontSize: 'px',
    },
    name: 'typography.title.h3',
    parent: 'global',
    rawValue: {
      fontFamily: '{fontFamily.inherit}',
      fontWeight: '{fontWeight.bold}',
      lineHeight: '{lineHeight.lg}',
      fontSize: '{fontSize.md}',
      textDecoration: '{textDecoration.none}',
    },
  },
  {
    type: 'typography',
    value: {
      fontFamily: 'inherit',
      fontWeight: '500',
      lineHeight: '150',
      fontSize: '14',
      textDecoration: 'none',
    },
    unit: {
      lineHeight: '%',
      fontSize: 'px',
    },
    name: 'typography.title.h4',
    parent: 'global',
    rawValue: {
      fontFamily: '{fontFamily.inherit}',
      fontWeight: '{fontWeight.bold}',
      lineHeight: '{lineHeight.lg}',
      fontSize: '{fontSize.sm}',
      textDecoration: '{textDecoration.none}',
    },
  },
  {
    type: 'typography',
    value: {
      fontFamily: 'inherit',
      fontWeight: '500',
      lineHeight: '175',
      fontSize: '12',
      textDecoration: 'none',
    },
    unit: {
      lineHeight: '%',
      fontSize: 'px',
    },
    name: 'typography.title.h5',
    parent: 'global',
    rawValue: {
      fontFamily: '{fontFamily.inherit}',
      fontWeight: '{fontWeight.bold}',
      lineHeight: '{lineHeight.xl}',
      fontSize: '{fontSize.xs}',
      textDecoration: '{textDecoration.none}',
    },
  },
  {
    type: 'typography',
    value: {
      fontFamily: 'inherit',
      fontWeight: '400',
      lineHeight: '175',
      fontSize: '14',
      textDecoration: 'none',
    },
    unit: {
      lineHeight: '%',
      fontSize: 'px',
    },
    name: 'typography.body.basic',
    parent: 'global',
    rawValue: {
      fontFamily: '{fontFamily.inherit}',
      fontWeight: '{fontWeight.regular}',
      lineHeight: '{lineHeight.xl}',
      fontSize: '{fontSize.sm}',
      textDecoration: '{textDecoration.none}',
    },
  },
  {
    type: 'typography',
    value: {
      fontFamily: 'inherit',
      fontWeight: '400',
      lineHeight: '175',
      fontSize: '12',
      textDecoration: 'none',
    },
    unit: {
      lineHeight: '%',
      fontSize: 'px',
    },
    name: 'typography.body.explain',
    parent: 'global',
    rawValue: {
      fontFamily: '{fontFamily.inherit}',
      fontWeight: '{fontWeight.regular}',
      lineHeight: '{lineHeight.xl}',
      fontSize: '{fontSize.xs}',
      textDecoration: '{textDecoration.none}',
    },
  },
  {
    type: 'typography',
    value: {
      fontFamily: 'inherit',
      fontWeight: '400',
      lineHeight: '175',
      fontSize: '12',
      textDecoration: 'underline',
    },
    unit: {
      lineHeight: '%',
      fontSize: 'px',
    },
    name: 'typography.body.underline',
    parent: 'global',
    rawValue: {
      fontFamily: '{fontFamily.inherit}',
      fontWeight: '{fontWeight.regular}',
      lineHeight: '{lineHeight.xl}',
      fontSize: '{fontSize.xs}',
      textDecoration: '{textDecoration.underline}',
    },
  },
  {
    value: 'none',
    type: 'textDecoration',
    name: 'textDecoration.none',
    parent: 'global',
    rawValue: 'none',
    resolveFailed: false,
  },
  {
    value: 'underline',
    type: 'textDecoration',
    name: 'textDecoration.underline',
    parent: 'global',
    rawValue: 'underline',
    resolveFailed: false,
  },
  {
    value: 'line-through',
    type: 'textDecoration',
    name: 'textDecoration.line-through',
    parent: 'global',
    rawValue: 'line-through',
    resolveFailed: false,
  },
];
