export const POLY = 'POLY_DESIGN';
export const POLY_SAVE = 'POLY_SAVE';
export const POLY_QUERY = 'POLY_QUERY';
export const POLY_REQUEST = 'POLY_REQUEST';
export const NAMESPACE_ROW = 'NAMESPACE_ROW';
export const GET_NAMESPACE_FULL_PATH = 'GET_NAMESPACE_FULL_PATH';
export const GET_REQUEST_NODE_API_LIST = 'GET_REQUEST_NODE_API_LIST';
