#!/bin/bash

set -euo pipefail

echo "copy files to web..."
ssh root@web mkdir -p /qxp/lib/qxp-web/dist
rsync -avz /tmp/dist/ root@web:/qxp/lib/qxp-web/dist/

ssh root@web mkdir -p /qxp/bin
scp /tmp/portal web:/tmp/portal
ssh root@web /qxp/scripts/reload_portal

rm -rf /tmp/dist /tmp/portal
